# Generated by Django 5.1 on 2024-08-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view instances'), ('can_create', 'Can create instances'), ('can_delete', 'Can delete instances'), ('can_edit', 'Can edit instance')]},
        ),
    ]
