# Generated by Django 5.1 on 2024-08-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view instances'), ('can_create', 'Can create instances'), ('can_delete', 'Can delete instances')]},
        ),
    ]
